name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          APP_DIR=~/app
          REPO_URL=https://github.com/brianxyz3/frontend-tesa-fullstack-lab.git
          BUILD_DIR=$APP_DIR/build
          APACHE_DIR=/var/www/html

          # Ensure required packages are installed
          if ! dpkg -s git >/dev/null 2>&1; then
              sudo apt update
              sudo apt install -y git
          fi

          if ! command -v node >/dev/null 2>&1; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt install -y nodejs
          fi

          if ! dpkg -s apache2 >/dev/null 2>&1; then
              sudo apt update
              sudo apt install -y apache2
              sudo systemctl enable apache2
              sudo systemctl start apache2
          fi

          # Go to app directory (create if missing)
          mkdir -p $APP_DIR
          rm -rf $APP_DIR/*
          cd $APP_DIR

          # Pull latest code
          if [ -d .git ]; then
            git reset --hard
            git pull
          else
            git clone $REPO_URL .
          fi

          # Install all dependencies & build React app
          npm install
          npm run build

          # Deploy build to Apache
          sudo rm -rf $APACHE_DIR/*
          sudo cp -r $BUILD_DIR/* $APACHE_DIR/

          # Adjust permissions
          sudo chown -R www-data:www-data $APACHE_DIR

          # Restart Apache
          sudo systemctl restart apache2
          sudo systemctl status apache2 --no-pager